language: java
dist: xenial
jdk:
  - openjdk8
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk-ea
script: ./mvnw clean verify -B
after_success:
  - "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} != '' ]] && ./mvnw deploy -B -DskipTests --settings settings.xml"
